### ISSUE TITLE
Settings text blank and no subtitles

### ISSUE THREAD

**Issue by iamfreee** [cguZZman/onedrive-kodi-addon#1]
Hi!  Thanks for the addon! 

The files list doesnt show the .srt files to add subtitles to the vídeo. 

Also the options menu is blank for all the texts. 

Thanks!

**Comment by cguZZman** [comment]
Thanks for let me know about the blank text in the settings. I'll fixed asap.
And about the subtitle, it will be automatically added to the video if the name it's exactly the same as the video. Even if the str file is not listed.

**Comment by iamfreee** [comment]
The subtitle is not being added, can you check that? 

Thanks!

**Comment by cguZZman** [comment]
The blank text in settings is fixed.
And I just checked the subtitle function and it was working as expected. I added a message in version 1.1.11 that tells if a subtitle was added or not to the video. 
If you see the message 'Subtitle not found for this video': make sure you have a ".srt" file in the same folder as the video, and the name must be exactly the same as the video name. p.e. if the video path is `/myfolder/myvideo.mp4` the subtitle file must be `/myfolder/myvideo.srt`
If you don't see the message at all, make sure you have this option checked in settings: "When playing videos, set the subtitle file located next to the video (.srt)"

Version 1.1.11 has been requested to be pushed in Kodi repository. It should be available to download soon, or you can download the zip from here and installed manually.
Let me know if the fix worked for you.

**Comment by iamfreee** [comment]
Hi,

Yes the blank text is fixed!

The subtitle works, i tested with simple names like 1.mkv and 1.srt and it worked!

But names with special chars like:
How I Met Your Mother S06E01 Big Days (1080p x265 Joy).mkv
How I Met Your Mother S06E01 Big Days (1080p x265 Joy).srt

The subtitle is not added.

Thanks!

**Comment by cguZZman** [comment]
That was a good example. The fix is commited.
Let me know if works for you.
Thanks

**Comment by iamfreee** [comment]
Works great now, thanks!
