### ISSUE TITLE
Support for onedrive business acounts

### ISSUE THREAD

**Issue by iamfreee** [cguZZman/onedrive-kodi-addon#2]
Hi!

Thanks for the great plugin!

When doing the login to the microsoft account to grant permissions, i can't use my business account email. Maybe there is another oauth2 endpoint for business accounts?

Thanks

**Comment by cguZZman** [comment]
Yes, the endpoint is different for business account. The problem is that Microsoft requires a business account (with some configuration done by the admin) to access it.
I'm still trying to find one.
I don't have an ETA, but I'm working on it.

**Comment by iamfreee** [comment]
Okay, many thanks!

I have one business account if you want one to test.

**Comment by cguZZman** [comment]
Thank you.
I have a business account from work. But I was trying to create the application within the Azure AD to support all all enterprise customers across all enterprise scenarios. But I don't have privileges to create an account there. The admin must grant me that, and that just won't happen.
So after some reading, I realized I can use the Azure AD v2.0 endpoint. 
There I can register applications which support business accounts. It won't support all kind of business accounts, but I think it should be good for the majority.

So good news, I have the application registered and I will be migrating the addon to the new endpoint soon.

**Comment by iamfreee** [comment]
Awesome news!

Thanks!

**Comment by cguZZman** [comment]
Support for business accounts has been added in version 1.2.0.
It's on its way to the official repository.
You can install it manually though.
