### ISSUE TITLE
mp3 file in shared folder fails to play

### ISSUE THREAD

**Issue by maxgrass** [cguZZman/onedrive-kodi-addon#5]
Hello, mp3 files are listed in the folder but when I start a file (PAPlayer, not .strm) it blinks 3-5 times like it tries to do something but fails to play.
 
Where are the logs so I can provide more relevant information?

I noticed that in the WebUI files in the OneDrive folder are queried in "Video" tab instead of the audio tab (but that may be a bug in the ui or unrelated).

kodi18 805

**Comment by cguZZman** [comment]
Hi Maxgrass, you can get the log location here: http://kodi.wiki/view/Log_file/Advanced#Location
or you can follow these instructions to get the log file with an addon: http://kodi.wiki/view/Log_file/Easy

Also can you describe the detailed steps you did to try to play the file?

To play music you must enter to the addon thru the Music menu > Music add-ons > OneDrive
And in the top left corner you should see the "Music / OneDrive" title.

**Comment by maxgrass** [comment]
Hello, I've updated Kodi and it seems to be working, including export of .strm files <3 With love.
